apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-metrics-adapter
  namespace: {{ .Values.namespace }}
  labels:
    application: kube-metrics-adapter
    version: {{ .Values.registry.imageTag }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      application: kube-metrics-adapter
  template:
    metadata:
      labels:
        application: kube-metrics-adapter
        version: {{ .Values.registry.imageTag }}
    spec:
      serviceAccountName: kube-metrics-adapter
      containers:
        - name: kube-metrics-adapter
          image: {{ .Values.registry.image}}:{{ .Values.registry.imageTag }}
          args:
            {{- if .Values.addDirectoryHeader }}
            - --add_dir_header={{ .Values.addDirectoryHeader }}
            {{- end}}
            {{- if .Values.log.alsoToStderr }}
            - --alsologtostderr={{ .Values.log.alsoToStderr }}
            {{- end}}
            {{- if .Values.authentication.kubeConfig }}
            - --authentication-kubeconfig={{ .Values.authentication.kubeConfig }}
            {{- end}}
            {{- if .Values.authentication.skipLookup }}
            - --authentication-skip-lookup={{ .Values.authentication.skipLookup }}
            {{- end}}
            {{- if .Values.authentication.tokenWebhookCacheTtl }}
            - --authentication-token-webhook-cache-ttl={{ .Values.authentication.tokenWebhookCacheTtl }}
            {{- end}}
            {{- if .Values.authentication.tolerateLookupFailure }}
            - --authentication-tolerate-lookup-failure={{ .Values.authentication.tolerateLookupFailure }}
            {{- end}}
            {{- if .Values.authorization.alwaysAllowPaths }}
            - --authorization-always-allow-paths={{ .Values.authorization.alwaysAllowPaths }}
            {{- end}}
            {{- if .Values.authorization.kubeConfig }}
            - --authorization-kubeconfig={{ .Values.authorization.kubeConfig }}
            {{- end}}
            {{- if .Values.authorization.webhookCache.authorizedTtl }}
            - --authorization-webhook-cache-authorized-ttl={{ .Values.authorization.webhookCache.authorizedTtl }}
            {{- end}}
            {{- if .Values.authorization.webhookCache.unauthorizedTtl }}
            - --authorization-webhook-cache-unauthorized-ttl={{ .Values.authorization.webhookCache.unauthorizedTtl }}
            {{- end}}
            {{- if .Values.aws.externalMetrics }}
            - --aws-external-metrics={{ .Values.aws.externalMetrics }}
            {{- end}}
            {{- if .Values.aws.region }}
            - --aws-region={{ .Values.aws.region }}
            {{- end}}
            {{- if .Values.tls.certificateDirectory }}
            - --cert-dir={{ .Values.tls.certificateDirectory }}
            {{- end}}
            {{- if .Values.tls.clientCaFile }}
            - --client-ca-file={{ .Values.tls.clientCaFile }}
            {{- end}}
            {{- if .Values.contentionProfiling }}
            - --contention-profiling={{ .Values.contentionProfiling }}
            {{- end}}
            {{- if .Values.credentialsDirectory }}
            - --credentials-dir={{ .Values.credentialsDirectory }}
            {{- end}}
            {{- if .Values.disregardIncompatibleHPAs }}
            - --disregard-incompatible-hpas={{ .Values.disregardIncompatibleHPAs }}
            {{- end}}
            {{- if .Values.enableCustomMetricsApi }}
            - --enable-custom-metrics-api={{ .Values.enableCustomMetricsApi }}
            {{- end}}
            {{- if .Values.enableExternalMetricsApi }}
            - --enable-external-metrics-api={{ .Values.enableExternalMetricsApi }}
            {{- end}}
            {{- if .Values.http2MaxStreamsPerConnection }}
            - --http2-max-streams-per-connection={{ .Values.http2MaxStreamsPerConnection }}
            {{- end}}
            {{- if .Values.influxDB.address }}
            - --influxdb-address={{ .Values.influxDB.address }}
            {{- end}}
            {{- if .Values.influxDB.organization }}
            - --influxdb-org={{ .Values.influxDB.organization }}
            {{- end}}
            {{- if .Values.influxDB.token }}
            - --influxdb-token={{ .Values.influxDB.token }}
            {{- end}}
            {{- if .Values.listerKubeConfig }}
            - --lister-kubeconfig={{ .Values.listerKubeConfig }}
            {{- end}}
            {{- if .Values.log.flushFrequency }}
            - --log-flush-frequency={{ .Values.log.flushFrequency }}
            {{- end}}
            {{- if .Values.log.backtraceAtTraceLocation }}
            - --log_backtrace_at={{ .Values.log.backtraceAtTraceLocation }}
            {{- end}}
            {{- if .Values.log.directory }}
            - --log_dir={{ .Values.log.directory }}
            {{- end}}
            {{- if .Values.log.file }}
            - --log_file={{ .Values.log.file }}
            {{- end}}
            {{- if .Values.log.fileMaxSize }}
            - --log_file_max_size={{ .Values.log.fileMaxSize }}
            {{- end}}
            {{- if .Values.log.toStderr }}
            - --logtostderr={{ .Values.log.toStderr }}
            {{- end}}
            {{- if .Values.prometheus.metricsAddress }}
            - --metrics-address={{ .Values.prometheus.metricsAddress }}
            {{- end}}
            {{- if .Values.profiling }}
            - --profiling={{ .Values.profiling }}
            {{- end}}
            {{- if .Values.prometheus.server }}
            - --prometheus-server={{ .Values.prometheus.server }}
            {{- end}}
            {{- if .Values.requestHeader.allowedNames }}
            - --requestheader-allowed-names={{ .Values.requestHeader.allowedNames }}
            {{- end}}
            {{- if .Values.requestHeader.clientCaFile }}
            - --requestheader-client-ca-file={{ .Values.requestHeader.clientCaFile }}
            {{- end}}
            {{- if .Values.requestHeader.extraHeadersPrefix }}
            - --requestheader-extra-headers-prefix={{ .Values.requestHeader.extraHeadersPrefix }}
            {{- end}}
            {{- if .Values.requestHeader.groupHeaders }}
            - --requestheader-group-headers={{ .Values.requestHeader.groupHeaders }}
            {{- end}}
            {{- if .Values.requestHeader.usernameHeaders }}
            - --requestheader-username-headers={{ .Values.requestHeader.usernameHeaders }}
            {{- end}}
            - --secure-port={{ .Values.service.internalPort }}
            {{- if .Values.log.skipHeaders }}
            - --skip_headers={{ .Values.log.skipHeaders }}
            {{- end}}
            {{- if .Values.log.skipLogHeaders }}
            - --skip_log_headers={{ .Values.log.skipLogHeaders }}
            {{- end}}
            {{- if .Values.skipperBackendsAnnotation }}
            - --skipper-backends-annotation={{ .Values.skipperBackendsAnnotation }}
            {{- end}}
            {{- if .Values.skipperIngressMetrics }}
            - --skipper-ingress-metrics={{ .Values.skipperIngressMetrics }}
            {{- end}}
            {{- if .Values.log.stderrThreshold }}
            - --stderrthreshold={{ .Values.log.stderrThreshold }}
            {{- end}}
            {{- if .Values.tls.certFile }}
            - --tls-cert-file={{ .Values.tls.certFile }}
            {{- end}}
            {{- if .Values.tls.cipherSuites }}
            - --tls-cipher-suites={{ .Values.tls.cipherSuites }}
            {{- end}}
            {{- if .Values.tls.minVersion }}
            - --tls-min-version={{ .Values.tls.minVersion }}
            {{- end}}
            {{- if .Values.tls.privateKeyFile }}
            - --tls-private-key-file={{ .Values.tls.privateKeyFile }}
            {{- end}}
            {{- if .Values.tls.sniCertKey }}
            - --tls-sni-cert-key={{ .Values.tls.sniCertKey }}
            {{- end}}
            {{- if .Values.token }}
            - --token={{ .Values.token }}
            {{- end}}
            {{- if .Values.log.level }}
            - --v={{ .Values.log.level }}
            {{- end}}
            {{- if .Values.vmodule }}
            - --vmodule={{ .Values.vmodule }}
            {{- end}}
            {{- if .Values.zmon.kariosdbEndpoint }}
            - --zmon-kariosdb-endpoint={{ .Values.zmon.kariosdbEndpoint }}
            {{- end}}
            {{- if .Values.zmon.tokenName }}
            - --zmon-token-name={{ .Values.zmon.tokenName }}
            {{- end}}
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
